### PR TITLE
NG inconvenience cost further constrained.

### PR DESCRIPTION
**Pull request by MariannaR**

### CODE REVIEW

**Review by johannah-pik — COMMENTED** [review]
What is with the Hotfix comment in the code? Is it still relevant?

**Comment by MariannaR** [comment]
yes, it is relevant still... in some countries, the NG cars are so cheap they get a very high share of the market (as it is still the case fro only CHA now). It is not elegant, but we have to constrain the inconvenience cost, otherwise we get very unreliable results

**Review by Loisel — APPROVED** [review]
Thanks for removing this random factor.

**Review by johannah-pik — APPROVED** [review]

**Comment by MariannaR** [comment]
Random factors are my personal favorite!

**Pull request merged**
